kind: pipeline
name: default

steps:
- name: build
  - pip install --upgrade pip setuptools wheel
  - pip wheel -r requirements.txt --wheel-dir=wheeldir --find-links=wheeldir
  - pip wheel -r requirements-dev.txt --wheel-dir=wheeldir --find-links=wheeldir
  - pip install --no-index --find-links=wheeldir -r requirements.txt
  - pip install --no-index --find-links=wheeldir -r requirements-dev.txt

- name: linter
  image: python:3.7
  commands:
  - pylava trading_bot

- name: tests
  image: python:3.7
  commands:
  - bash -c pwd
  - PYTHONPATH=../ pytest .


services:
- name: redis
  image: redis
