kind: pipeline
name: default

steps:
- name: linter
  image: python:3.7
  volumes:
  - name: cache
    path: wheeldir
  commands:
  - pip install pylava
  - pylava trading_bot

- name: tests
  image: python:3.7
  commands:
  - bash -c pwd
  - pip install -r requirements-dev.txt
  - PYTHONPATH=../ pytest .

services:
- name: redis
  image: redis
