version: '2'
services:
  proxy:
    image: zzrot/alpine-caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./.caddy:/root/.caddy
    networks:
      - server-net
    environment:
      - APP_HOST_URL=prodhooks.pavkazzz.ru

  bot-server:
    image: pavkazzz/telegram_bot:hooks-prod-v1.0
    restart: always
    expose:
      - 80
    environment:
      - RHOST=redis
      - APP_REDIS_URL=redis
      - APP_HOST_URL=prodhooks.pavkazzz.ru
    volumes:
      - ./data:/app/data
    networks:
      - server-net
    depends_on:
      - proxy
      - redis

  redis:
    image: redis:5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - server-net
    volumes:
      - redis-data:/data

networks:
  server-net:

volumes:
  redis-data:
