version: '3'
services:
  proxy:
    image: zzrot/alpine-caddy
    ports:
      - 443:80
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./.caddy:/root/.caddy
    networks:
      - redis-net
  app:
    image: pavkazzz/telegram_bot:hooks-v0.2
    command: ["python", "./trading_bot/async_webserver.py", "--redis-url", "redis"]
    environment:
      - RHOST=redis
    networks:
      - redis-net
    depends_on:
      - redis
    volumes:
      - ./data:/app/data
      - ./.caddy:/app/.caddy

  redis:
    image: redis:5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data

networks:
  redis-net:

volumes:
  redis-data:
